sudo: required


language: go
go:
  - "1.13"

services:
  - docker

env:
  - GO111MODULE=on

install: true

script:
  # start etcd registry  insecure listen in [:]:2379
  - docker run -d --network host k8s.gcr.io/etcd:3.3.10 etcd
  # start zookeeper registry insecure listen in [:]:2181
  - docker run -d --network host zookeeper
  # start consul registry insecure listen in [:]:8500
  - docker run -d --network host consul
  # start nacos registry insecure listen in [:]:8848
  - docker run -d --network host nacos/nacos-server:latest
  - go fmt ./... && [[ -z `git status -s` ]]
  - sh before_validate_license.sh
  - chmod u+x /tmp/tools/license/license-header-checker
  - /tmp/tools/license/license-header-checker -v -a -r -i vendor  /tmp/tools/license/license.txt . go  && [[ -z `git status -s` ]]
  - chmod u+x before_ut.sh && ./before_ut.sh
  - go mod vendor && go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=f5d6237f2c79db584e75604f7f88db1ce1673c8c0e98451217b28fde791e1d4f
